

export const sample_foods: any[]=[
    {
      id: '1a',
      name: 'Pizza Margherita',
      price: 12.99,
      tags: ['Pizza', 'Italian',],
      favorite: false,
      stars: 4,
      imageUrl: 'assets/food-pizza_magherita.jpeg',
      origin: ['Italy'],
      cookTime: '30 minutes',
    },
    {
      id: '2b',
      name: 'Burger Deluxe',
      price: 9.99,
      tags: ['Burger', 'American','Fast Food'],
      favorite: true,
      stars: 5,
      imageUrl: 'assets/food-burger_deluxe.jpeg',
      origin: ['USA'],
      cookTime: '20 minutes',
    },
    {
      id: '3c',
      name: 'Sushi Combo',
      price: 18.50,
      tags: ['Sushi', 'Japanese'],
      favorite: false,
      stars: 4.5,
      imageUrl: 'assets/food-sushi_combo.jpeg',
      origin: ['Japan'],
      cookTime: '40 minutes',
    },
    {
        id: 'easter_egg',
        name: 'Sarmale',
        price: 16.25,
        tags: ['Traditional', 'Romanian'],
        favorite: true,
        stars: 4.7,
        imageUrl: 'assets/food-sarmale.jpeg',
        origin: ['Romania'],
        cookTime: '2 hours',
      },
      {
        id: '5',
        name: 'Paine pe Vatră',
        price: 6.50,
        tags: ['Traditional', 'Romanian'],
        favorite: false,
        stars: 4.6,
        imageUrl: 'assets/food-paine_pe_vatra.jpeg',
        origin: ['Romania'],
        cookTime: '1 hour',
      },
      {
        id: '6',
        name: 'Ciorbă de Burtă',
        price: 13.75,
        tags: ['Soup', 'Traditional', 'Romanian'],
        favorite: false,
        stars: 4.3,
        imageUrl: 'assets/food-ciorba_de_burta.jpeg',
        origin: ['Romania'],
        cookTime: '1.5 hours',
      },
      {
        id: '7',
        name: 'Mici Combo',
        price: 110.00,
        tags: ['Grill', 'Traditional', 'Romanian'],
        favorite: true,
        stars: 4.8,
        imageUrl: 'assets/food-mici_combo.jpeg',
        origin: ['Romania'],
        cookTime: '30 minutes',
      },
      {
      id:'8',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/food-pizza_peperoni.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'9',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/food-meatball.jpeg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'10',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/food-hamburger.jpeg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'11',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/food-cartofi_prajiti.jpeg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'12',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/food-supa_de_pui.jpeg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'13',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food-pizza_vegetala.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
    // Add more food items as needed
  ];


  export const sample_tags: any[] = [
    { name: 'All', count: 7 },
    { name: 'Fast Food', count: 1 },
    { name: 'Italian', count: 1 },
    { name: 'American', count: 1 },
    { name: 'Japanese', count: 1 },
    { name: 'Traditional', count: 4 },
    { name: 'Romanian', count: 4 },
    // Add more tags as needed
  ];

  export const sample_users: any[] = [
    {
      
      name: "John Doe",
      email: "john@gmail.com",
      password: "12345",
      address: "Toronto On",
      isAdmin: true,
    },
    {
      
      name: "Jane Doe",
      email: "Jane@gmail.com",
      password: "12345",
      address: "Shanghai",
      isAdmin: false,
    },
  ];